default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: recipe_app_dev_db

test:
  <<: *default
  database: recipe_app_test_db

production:
  <<: *default
  database: rails_recipe_app_production
  username: rails_recipe_app
  password: <%= ENV["RAILS_RECIPE_APP_DATABASE_PASSWORD"] %>
